version: '3.4'

services:
  info-api:
    image: infoapi
    container_name: infoapi
    restart: always
    build:
      context: ./stats/
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/smite_god_info
        - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
    ports:
      - 8081:8081
    depends_on:
      - db

  stats-api:
    image: statsapi
    container_name: statsapi
    restart: always
    build:
      context: ./stats/
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/smite_gods_stats
        - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
    ports:
      - 8082:8080
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    environment:
        # So you don't have to use root, but you can if you like
        # MYSQL_USER: 'user'
        # MYSQL_PASSWORD: ${DB_PASS}
        # Password for root access
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
        - ./db/init:/docker-entrypoint-initdb.d/:ro
    ports:
        - 3308:3306
