name: End to End Testing and Dockerizing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-front-end:
    name: Builds the front-end and runs it
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smitearific_web_app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ui/node_modules
            ~/.cache/Cypress
            ${{ github.workspace }}/smitearific_web_app/.next/cache
          key: |
            ${{ runner.os }}-node-${{ hashFiles('**/ui/package-lock.json') }}
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        run: npm install
      - name: Build front-end
        run: npm run build
        
  build-info-api:
    name: Build the Info API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smitearific_api/info
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      

      - name: Build the Info API with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: info
          path: smitearific_api/info/target/*.jar
        
  build-stats-api:
    name: Build the Stats API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smitearific_api/stats
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      

      - name: Build the Stats API with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: stats
          path: smitearific_api/stats/target/*.jar
  
  run-backend-with-docker:
    name: Runs the APIs and Database in a docker container
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
    needs: [build-info-api, build-stats-api]
    defaults:
      run:
        working-directory: smitearific_api
    steps:
      - uses: actions/checkout@v2
      - name: Downaload info jar
        uses: actions/download-artifact@v2
        with:
          name: info
          path: smitearific_api/info/target/

      - name: Downaload stas jar
        uses: actions/download-artifact@v2
        with:
          name: stats
          path: smitearific_api/stats/target/
      
      - name: Build Docker images
        run: docker-compose build
      
      - name: Run docker container
        run: docker-compose up -d

#   run-e2e-tests:
#     name: Runs Cypress e2e tests
#     runs-on: ubuntu-latest
#     needs: [build-front-end, run-backend-with-docker]
    
